server:
  port: 7001
spring:
  application:
    name: server
#  security:
#    user:
#      name: root
#      password: 123
##是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
eureka:
  client:
    register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
    #设置服务注册中心的URL，用于client和server端交流 http://localhost:${server.port}/eureka/
    service-url:
#      defaultZone: http://root:123@localhost:7001/eureka/
      defaultZone: http://localhost:7001/eureka/

#  instance:
#    appname: server1
